### ISSUE TITLE
Nesting limit

### ISSUE THREAD

**Issue by Dudaevskiy** [pamtbaau/grav-plugin-labeltree#2]
I understand that thanks to the plugin, nesting of at most two levels is possible? Is it possible to make nesting more?

**Comment by pamtbaau** [comment]
Nesting is already unlimited....

**Comment by Dudaevskiy** [comment]
At the moment with this variant of nesting I get an error
labels:
    - Label-1:
        - Label-11
              - Label-112
                   - Label-1123
    - Label-2:
        - Label-22

**Comment by pamtbaau** [comment]
Syntactically your 'labeling' looks ok.

When I use:
```
labels:
    - label-a1:
        - label-a11:
            - label-a111
        - label-a12:
            - label-a121
    - label-b1:
        - label-b11:
            - label-b111:
                - label-b1111
    - label-c1
```
I get no error and all goes well...

What error do you get? English please....
