### ISSUE TITLE
Does the plugin support the ability to display entries on another page?

### ISSUE THREAD

**Issue by Dudaevskiy** [pamtbaau/grav-plugin-labeltree#4]
At the moment I use to display on the other page categories of entries using the code below:

```
`title: WEB
date: '2018-09-01 05:19'
content:
    items:
        '@taxonomy.labels': WEB
    leading: 0
    columns: 1
    limit: 6
    order:
        by: date
        dir: desc
    show_date: false
    pagination: true
    url_taxonomy_filters: false`
```
Can I specify the location of the parameter:
`'@ taxonomy.category': WEB`
Assume:
`'@ taxonomy.labels': WEB](url)`
